// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2021.1 (64-bit)
// Version: 2021.1
// Copyright (C) Copyright 1986-2021 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="fir_fixed_fir_fixed,hls_ip_2021_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg400-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=7.300000,HLS_SYN_LAT=1115,HLS_SYN_TPT=none,HLS_SYN_MEM=8,HLS_SYN_DSP=0,HLS_SYN_FF=11556,HLS_SYN_LUT=7592,HLS_VERSION=2021_1}" *)

module fir_fixed (
        ap_clk,
        ap_rst_n,
        m_axi_gmem0_AWVALID,
        m_axi_gmem0_AWREADY,
        m_axi_gmem0_AWADDR,
        m_axi_gmem0_AWID,
        m_axi_gmem0_AWLEN,
        m_axi_gmem0_AWSIZE,
        m_axi_gmem0_AWBURST,
        m_axi_gmem0_AWLOCK,
        m_axi_gmem0_AWCACHE,
        m_axi_gmem0_AWPROT,
        m_axi_gmem0_AWQOS,
        m_axi_gmem0_AWREGION,
        m_axi_gmem0_AWUSER,
        m_axi_gmem0_WVALID,
        m_axi_gmem0_WREADY,
        m_axi_gmem0_WDATA,
        m_axi_gmem0_WSTRB,
        m_axi_gmem0_WLAST,
        m_axi_gmem0_WID,
        m_axi_gmem0_WUSER,
        m_axi_gmem0_ARVALID,
        m_axi_gmem0_ARREADY,
        m_axi_gmem0_ARADDR,
        m_axi_gmem0_ARID,
        m_axi_gmem0_ARLEN,
        m_axi_gmem0_ARSIZE,
        m_axi_gmem0_ARBURST,
        m_axi_gmem0_ARLOCK,
        m_axi_gmem0_ARCACHE,
        m_axi_gmem0_ARPROT,
        m_axi_gmem0_ARQOS,
        m_axi_gmem0_ARREGION,
        m_axi_gmem0_ARUSER,
        m_axi_gmem0_RVALID,
        m_axi_gmem0_RREADY,
        m_axi_gmem0_RDATA,
        m_axi_gmem0_RLAST,
        m_axi_gmem0_RID,
        m_axi_gmem0_RUSER,
        m_axi_gmem0_RRESP,
        m_axi_gmem0_BVALID,
        m_axi_gmem0_BREADY,
        m_axi_gmem0_BRESP,
        m_axi_gmem0_BID,
        m_axi_gmem0_BUSER,
        m_axi_gmem1_AWVALID,
        m_axi_gmem1_AWREADY,
        m_axi_gmem1_AWADDR,
        m_axi_gmem1_AWID,
        m_axi_gmem1_AWLEN,
        m_axi_gmem1_AWSIZE,
        m_axi_gmem1_AWBURST,
        m_axi_gmem1_AWLOCK,
        m_axi_gmem1_AWCACHE,
        m_axi_gmem1_AWPROT,
        m_axi_gmem1_AWQOS,
        m_axi_gmem1_AWREGION,
        m_axi_gmem1_AWUSER,
        m_axi_gmem1_WVALID,
        m_axi_gmem1_WREADY,
        m_axi_gmem1_WDATA,
        m_axi_gmem1_WSTRB,
        m_axi_gmem1_WLAST,
        m_axi_gmem1_WID,
        m_axi_gmem1_WUSER,
        m_axi_gmem1_ARVALID,
        m_axi_gmem1_ARREADY,
        m_axi_gmem1_ARADDR,
        m_axi_gmem1_ARID,
        m_axi_gmem1_ARLEN,
        m_axi_gmem1_ARSIZE,
        m_axi_gmem1_ARBURST,
        m_axi_gmem1_ARLOCK,
        m_axi_gmem1_ARCACHE,
        m_axi_gmem1_ARPROT,
        m_axi_gmem1_ARQOS,
        m_axi_gmem1_ARREGION,
        m_axi_gmem1_ARUSER,
        m_axi_gmem1_RVALID,
        m_axi_gmem1_RREADY,
        m_axi_gmem1_RDATA,
        m_axi_gmem1_RLAST,
        m_axi_gmem1_RID,
        m_axi_gmem1_RUSER,
        m_axi_gmem1_RRESP,
        m_axi_gmem1_BVALID,
        m_axi_gmem1_BREADY,
        m_axi_gmem1_BRESP,
        m_axi_gmem1_BID,
        m_axi_gmem1_BUSER,
        s_axi_control_AWVALID,
        s_axi_control_AWREADY,
        s_axi_control_AWADDR,
        s_axi_control_WVALID,
        s_axi_control_WREADY,
        s_axi_control_WDATA,
        s_axi_control_WSTRB,
        s_axi_control_ARVALID,
        s_axi_control_ARREADY,
        s_axi_control_ARADDR,
        s_axi_control_RVALID,
        s_axi_control_RREADY,
        s_axi_control_RDATA,
        s_axi_control_RRESP,
        s_axi_control_BVALID,
        s_axi_control_BREADY,
        s_axi_control_BRESP,
        interrupt
);

parameter    ap_ST_fsm_state1 = 15'd1;
parameter    ap_ST_fsm_state2 = 15'd2;
parameter    ap_ST_fsm_state3 = 15'd4;
parameter    ap_ST_fsm_state4 = 15'd8;
parameter    ap_ST_fsm_state5 = 15'd16;
parameter    ap_ST_fsm_state6 = 15'd32;
parameter    ap_ST_fsm_state7 = 15'd64;
parameter    ap_ST_fsm_state8 = 15'd128;
parameter    ap_ST_fsm_state9 = 15'd256;
parameter    ap_ST_fsm_state10 = 15'd512;
parameter    ap_ST_fsm_state11 = 15'd1024;
parameter    ap_ST_fsm_state12 = 15'd2048;
parameter    ap_ST_fsm_state13 = 15'd4096;
parameter    ap_ST_fsm_state14 = 15'd8192;
parameter    ap_ST_fsm_state15 = 15'd16384;
parameter    C_S_AXI_CONTROL_DATA_WIDTH = 32;
parameter    C_S_AXI_CONTROL_ADDR_WIDTH = 6;
parameter    C_S_AXI_DATA_WIDTH = 32;
parameter    C_M_AXI_GMEM0_ID_WIDTH = 1;
parameter    C_M_AXI_GMEM0_ADDR_WIDTH = 64;
parameter    C_M_AXI_GMEM0_DATA_WIDTH = 32;
parameter    C_M_AXI_GMEM0_AWUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM0_ARUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM0_WUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM0_RUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM0_BUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM0_USER_VALUE = 0;
parameter    C_M_AXI_GMEM0_PROT_VALUE = 0;
parameter    C_M_AXI_GMEM0_CACHE_VALUE = 3;
parameter    C_M_AXI_DATA_WIDTH = 32;
parameter    C_M_AXI_GMEM1_ID_WIDTH = 1;
parameter    C_M_AXI_GMEM1_ADDR_WIDTH = 64;
parameter    C_M_AXI_GMEM1_DATA_WIDTH = 32;
parameter    C_M_AXI_GMEM1_AWUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM1_ARUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM1_WUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM1_RUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM1_BUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM1_USER_VALUE = 0;
parameter    C_M_AXI_GMEM1_PROT_VALUE = 0;
parameter    C_M_AXI_GMEM1_CACHE_VALUE = 3;

parameter C_S_AXI_CONTROL_WSTRB_WIDTH = (32 / 8);
parameter C_S_AXI_WSTRB_WIDTH = (32 / 8);
parameter C_M_AXI_GMEM0_WSTRB_WIDTH = (32 / 8);
parameter C_M_AXI_WSTRB_WIDTH = (32 / 8);
parameter C_M_AXI_GMEM1_WSTRB_WIDTH = (32 / 8);

input   ap_clk;
input   ap_rst_n;
output   m_axi_gmem0_AWVALID;
input   m_axi_gmem0_AWREADY;
output  [C_M_AXI_GMEM0_ADDR_WIDTH - 1:0] m_axi_gmem0_AWADDR;
output  [C_M_AXI_GMEM0_ID_WIDTH - 1:0] m_axi_gmem0_AWID;
output  [7:0] m_axi_gmem0_AWLEN;
output  [2:0] m_axi_gmem0_AWSIZE;
output  [1:0] m_axi_gmem0_AWBURST;
output  [1:0] m_axi_gmem0_AWLOCK;
output  [3:0] m_axi_gmem0_AWCACHE;
output  [2:0] m_axi_gmem0_AWPROT;
output  [3:0] m_axi_gmem0_AWQOS;
output  [3:0] m_axi_gmem0_AWREGION;
output  [C_M_AXI_GMEM0_AWUSER_WIDTH - 1:0] m_axi_gmem0_AWUSER;
output   m_axi_gmem0_WVALID;
input   m_axi_gmem0_WREADY;
output  [C_M_AXI_GMEM0_DATA_WIDTH - 1:0] m_axi_gmem0_WDATA;
output  [C_M_AXI_GMEM0_WSTRB_WIDTH - 1:0] m_axi_gmem0_WSTRB;
output   m_axi_gmem0_WLAST;
output  [C_M_AXI_GMEM0_ID_WIDTH - 1:0] m_axi_gmem0_WID;
output  [C_M_AXI_GMEM0_WUSER_WIDTH - 1:0] m_axi_gmem0_WUSER;
output   m_axi_gmem0_ARVALID;
input   m_axi_gmem0_ARREADY;
output  [C_M_AXI_GMEM0_ADDR_WIDTH - 1:0] m_axi_gmem0_ARADDR;
output  [C_M_AXI_GMEM0_ID_WIDTH - 1:0] m_axi_gmem0_ARID;
output  [7:0] m_axi_gmem0_ARLEN;
output  [2:0] m_axi_gmem0_ARSIZE;
output  [1:0] m_axi_gmem0_ARBURST;
output  [1:0] m_axi_gmem0_ARLOCK;
output  [3:0] m_axi_gmem0_ARCACHE;
output  [2:0] m_axi_gmem0_ARPROT;
output  [3:0] m_axi_gmem0_ARQOS;
output  [3:0] m_axi_gmem0_ARREGION;
output  [C_M_AXI_GMEM0_ARUSER_WIDTH - 1:0] m_axi_gmem0_ARUSER;
input   m_axi_gmem0_RVALID;
output   m_axi_gmem0_RREADY;
input  [C_M_AXI_GMEM0_DATA_WIDTH - 1:0] m_axi_gmem0_RDATA;
input   m_axi_gmem0_RLAST;
input  [C_M_AXI_GMEM0_ID_WIDTH - 1:0] m_axi_gmem0_RID;
input  [C_M_AXI_GMEM0_RUSER_WIDTH - 1:0] m_axi_gmem0_RUSER;
input  [1:0] m_axi_gmem0_RRESP;
input   m_axi_gmem0_BVALID;
output   m_axi_gmem0_BREADY;
input  [1:0] m_axi_gmem0_BRESP;
input  [C_M_AXI_GMEM0_ID_WIDTH - 1:0] m_axi_gmem0_BID;
input  [C_M_AXI_GMEM0_BUSER_WIDTH - 1:0] m_axi_gmem0_BUSER;
output   m_axi_gmem1_AWVALID;
input   m_axi_gmem1_AWREADY;
output  [C_M_AXI_GMEM1_ADDR_WIDTH - 1:0] m_axi_gmem1_AWADDR;
output  [C_M_AXI_GMEM1_ID_WIDTH - 1:0] m_axi_gmem1_AWID;
output  [7:0] m_axi_gmem1_AWLEN;
output  [2:0] m_axi_gmem1_AWSIZE;
output  [1:0] m_axi_gmem1_AWBURST;
output  [1:0] m_axi_gmem1_AWLOCK;
output  [3:0] m_axi_gmem1_AWCACHE;
output  [2:0] m_axi_gmem1_AWPROT;
output  [3:0] m_axi_gmem1_AWQOS;
output  [3:0] m_axi_gmem1_AWREGION;
output  [C_M_AXI_GMEM1_AWUSER_WIDTH - 1:0] m_axi_gmem1_AWUSER;
output   m_axi_gmem1_WVALID;
input   m_axi_gmem1_WREADY;
output  [C_M_AXI_GMEM1_DATA_WIDTH - 1:0] m_axi_gmem1_WDATA;
output  [C_M_AXI_GMEM1_WSTRB_WIDTH - 1:0] m_axi_gmem1_WSTRB;
output   m_axi_gmem1_WLAST;
output  [C_M_AXI_GMEM1_ID_WIDTH - 1:0] m_axi_gmem1_WID;
output  [C_M_AXI_GMEM1_WUSER_WIDTH - 1:0] m_axi_gmem1_WUSER;
output   m_axi_gmem1_ARVALID;
input   m_axi_gmem1_ARREADY;
output  [C_M_AXI_GMEM1_ADDR_WIDTH - 1:0] m_axi_gmem1_ARADDR;
output  [C_M_AXI_GMEM1_ID_WIDTH - 1:0] m_axi_gmem1_ARID;
output  [7:0] m_axi_gmem1_ARLEN;
output  [2:0] m_axi_gmem1_ARSIZE;
output  [1:0] m_axi_gmem1_ARBURST;
output  [1:0] m_axi_gmem1_ARLOCK;
output  [3:0] m_axi_gmem1_ARCACHE;
output  [2:0] m_axi_gmem1_ARPROT;
output  [3:0] m_axi_gmem1_ARQOS;
output  [3:0] m_axi_gmem1_ARREGION;
output  [C_M_AXI_GMEM1_ARUSER_WIDTH - 1:0] m_axi_gmem1_ARUSER;
input   m_axi_gmem1_RVALID;
output   m_axi_gmem1_RREADY;
input  [C_M_AXI_GMEM1_DATA_WIDTH - 1:0] m_axi_gmem1_RDATA;
input   m_axi_gmem1_RLAST;
input  [C_M_AXI_GMEM1_ID_WIDTH - 1:0] m_axi_gmem1_RID;
input  [C_M_AXI_GMEM1_RUSER_WIDTH - 1:0] m_axi_gmem1_RUSER;
input  [1:0] m_axi_gmem1_RRESP;
input   m_axi_gmem1_BVALID;
output   m_axi_gmem1_BREADY;
input  [1:0] m_axi_gmem1_BRESP;
input  [C_M_AXI_GMEM1_ID_WIDTH - 1:0] m_axi_gmem1_BID;
input  [C_M_AXI_GMEM1_BUSER_WIDTH - 1:0] m_axi_gmem1_BUSER;
input   s_axi_control_AWVALID;
output   s_axi_control_AWREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_AWADDR;
input   s_axi_control_WVALID;
output   s_axi_control_WREADY;
input  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_WDATA;
input  [C_S_AXI_CONTROL_WSTRB_WIDTH - 1:0] s_axi_control_WSTRB;
input   s_axi_control_ARVALID;
output   s_axi_control_ARREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_ARADDR;
output   s_axi_control_RVALID;
input   s_axi_control_RREADY;
output  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_RDATA;
output  [1:0] s_axi_control_RRESP;
output   s_axi_control_BVALID;
input   s_axi_control_BREADY;
output  [1:0] s_axi_control_BRESP;
output   interrupt;

 reg    ap_rst_n_inv;
wire    ap_start;
reg    ap_done;
reg    ap_idle;
(* fsm_encoding = "none" *) reg   [14:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    ap_ready;
wire   [63:0] input_r;
wire   [63:0] output_r;
reg    gmem0_blk_n_AR;
wire    ap_CS_fsm_state2;
reg    gmem1_blk_n_AW;
wire    ap_CS_fsm_state8;
reg    gmem1_blk_n_B;
wire    ap_CS_fsm_state15;
reg   [61:0] trunc_ln_reg_429;
reg   [61:0] trunc_ln39_1_reg_435;
wire    grp_fir_fixed_Pipeline_VITIS_LOOP_39_1_fu_233_ap_start;
wire    grp_fir_fixed_Pipeline_VITIS_LOOP_39_1_fu_233_ap_done;
wire    grp_fir_fixed_Pipeline_VITIS_LOOP_39_1_fu_233_ap_idle;
wire    grp_fir_fixed_Pipeline_VITIS_LOOP_39_1_fu_233_ap_ready;
wire    grp_fir_fixed_Pipeline_VITIS_LOOP_39_1_fu_233_m_axi_gmem0_AWVALID;
wire   [63:0] grp_fir_fixed_Pipeline_VITIS_LOOP_39_1_fu_233_m_axi_gmem0_AWADDR;
wire   [0:0] grp_fir_fixed_Pipeline_VITIS_LOOP_39_1_fu_233_m_axi_gmem0_AWID;
wire   [31:0] grp_fir_fixed_Pipeline_VITIS_LOOP_39_1_fu_233_m_axi_gmem0_AWLEN;
wire   [2:0] grp_fir_fixed_Pipeline_VITIS_LOOP_39_1_fu_233_m_axi_gmem0_AWSIZE;
wire   [1:0] grp_fir_fixed_Pipeline_VITIS_LOOP_39_1_fu_233_m_axi_gmem0_AWBURST;
wire   [1:0] grp_fir_fixed_Pipeline_VITIS_LOOP_39_1_fu_233_m_axi_gmem0_AWLOCK;
wire   [3:0] grp_fir_fixed_Pipeline_VITIS_LOOP_39_1_fu_233_m_axi_gmem0_AWCACHE;
wire   [2:0] grp_fir_fixed_Pipeline_VITIS_LOOP_39_1_fu_233_m_axi_gmem0_AWPROT;
wire   [3:0] grp_fir_fixed_Pipeline_VITIS_LOOP_39_1_fu_233_m_axi_gmem0_AWQOS;
wire   [3:0] grp_fir_fixed_Pipeline_VITIS_LOOP_39_1_fu_233_m_axi_gmem0_AWREGION;
wire   [0:0] grp_fir_fixed_Pipeline_VITIS_LOOP_39_1_fu_233_m_axi_gmem0_AWUSER;
wire    grp_fir_fixed_Pipeline_VITIS_LOOP_39_1_fu_233_m_axi_gmem0_WVALID;
wire   [31:0] grp_fir_fixed_Pipeline_VITIS_LOOP_39_1_fu_233_m_axi_gmem0_WDATA;
wire   [3:0] grp_fir_fixed_Pipeline_VITIS_LOOP_39_1_fu_233_m_axi_gmem0_WSTRB;
wire    grp_fir_fixed_Pipeline_VITIS_LOOP_39_1_fu_233_m_axi_gmem0_WLAST;
wire   [0:0] grp_fir_fixed_Pipeline_VITIS_LOOP_39_1_fu_233_m_axi_gmem0_WID;
wire   [0:0] grp_fir_fixed_Pipeline_VITIS_LOOP_39_1_fu_233_m_axi_gmem0_WUSER;
wire    grp_fir_fixed_Pipeline_VITIS_LOOP_39_1_fu_233_m_axi_gmem0_ARVALID;
wire   [63:0] grp_fir_fixed_Pipeline_VITIS_LOOP_39_1_fu_233_m_axi_gmem0_ARADDR;
wire   [0:0] grp_fir_fixed_Pipeline_VITIS_LOOP_39_1_fu_233_m_axi_gmem0_ARID;
wire   [31:0] grp_fir_fixed_Pipeline_VITIS_LOOP_39_1_fu_233_m_axi_gmem0_ARLEN;
wire   [2:0] grp_fir_fixed_Pipeline_VITIS_LOOP_39_1_fu_233_m_axi_gmem0_ARSIZE;
wire   [1:0] grp_fir_fixed_Pipeline_VITIS_LOOP_39_1_fu_233_m_axi_gmem0_ARBURST;
wire   [1:0] grp_fir_fixed_Pipeline_VITIS_LOOP_39_1_fu_233_m_axi_gmem0_ARLOCK;
wire   [3:0] grp_fir_fixed_Pipeline_VITIS_LOOP_39_1_fu_233_m_axi_gmem0_ARCACHE;
wire   [2:0] grp_fir_fixed_Pipeline_VITIS_LOOP_39_1_fu_233_m_axi_gmem0_ARPROT;
wire   [3:0] grp_fir_fixed_Pipeline_VITIS_LOOP_39_1_fu_233_m_axi_gmem0_ARQOS;
wire   [3:0] grp_fir_fixed_Pipeline_VITIS_LOOP_39_1_fu_233_m_axi_gmem0_ARREGION;
wire   [0:0] grp_fir_fixed_Pipeline_VITIS_LOOP_39_1_fu_233_m_axi_gmem0_ARUSER;
wire    grp_fir_fixed_Pipeline_VITIS_LOOP_39_1_fu_233_m_axi_gmem0_RREADY;
wire    grp_fir_fixed_Pipeline_VITIS_LOOP_39_1_fu_233_m_axi_gmem0_BREADY;
wire    grp_fir_fixed_Pipeline_VITIS_LOOP_39_1_fu_233_m_axi_gmem1_AWVALID;
wire   [63:0] grp_fir_fixed_Pipeline_VITIS_LOOP_39_1_fu_233_m_axi_gmem1_AWADDR;
wire   [0:0] grp_fir_fixed_Pipeline_VITIS_LOOP_39_1_fu_233_m_axi_gmem1_AWID;
wire   [31:0] grp_fir_fixed_Pipeline_VITIS_LOOP_39_1_fu_233_m_axi_gmem1_AWLEN;
wire   [2:0] grp_fir_fixed_Pipeline_VITIS_LOOP_39_1_fu_233_m_axi_gmem1_AWSIZE;
wire   [1:0] grp_fir_fixed_Pipeline_VITIS_LOOP_39_1_fu_233_m_axi_gmem1_AWBURST;
wire   [1:0] grp_fir_fixed_Pipeline_VITIS_LOOP_39_1_fu_233_m_axi_gmem1_AWLOCK;
wire   [3:0] grp_fir_fixed_Pipeline_VITIS_LOOP_39_1_fu_233_m_axi_gmem1_AWCACHE;
wire   [2:0] grp_fir_fixed_Pipeline_VITIS_LOOP_39_1_fu_233_m_axi_gmem1_AWPROT;
wire   [3:0] grp_fir_fixed_Pipeline_VITIS_LOOP_39_1_fu_233_m_axi_gmem1_AWQOS;
wire   [3:0] grp_fir_fixed_Pipeline_VITIS_LOOP_39_1_fu_233_m_axi_gmem1_AWREGION;
wire   [0:0] grp_fir_fixed_Pipeline_VITIS_LOOP_39_1_fu_233_m_axi_gmem1_AWUSER;
wire    grp_fir_fixed_Pipeline_VITIS_LOOP_39_1_fu_233_m_axi_gmem1_WVALID;
wire   [31:0] grp_fir_fixed_Pipeline_VITIS_LOOP_39_1_fu_233_m_axi_gmem1_WDATA;
wire   [3:0] grp_fir_fixed_Pipeline_VITIS_LOOP_39_1_fu_233_m_axi_gmem1_WSTRB;
wire    grp_fir_fixed_Pipeline_VITIS_LOOP_39_1_fu_233_m_axi_gmem1_WLAST;
wire   [0:0] grp_fir_fixed_Pipeline_VITIS_LOOP_39_1_fu_233_m_axi_gmem1_WID;
wire   [0:0] grp_fir_fixed_Pipeline_VITIS_LOOP_39_1_fu_233_m_axi_gmem1_WUSER;
wire    grp_fir_fixed_Pipeline_VITIS_LOOP_39_1_fu_233_m_axi_gmem1_ARVALID;
wire   [63:0] grp_fir_fixed_Pipeline_VITIS_LOOP_39_1_fu_233_m_axi_gmem1_ARADDR;
wire   [0:0] grp_fir_fixed_Pipeline_VITIS_LOOP_39_1_fu_233_m_axi_gmem1_ARID;
wire   [31:0] grp_fir_fixed_Pipeline_VITIS_LOOP_39_1_fu_233_m_axi_gmem1_ARLEN;
wire   [2:0] grp_fir_fixed_Pipeline_VITIS_LOOP_39_1_fu_233_m_axi_gmem1_ARSIZE;
wire   [1:0] grp_fir_fixed_Pipeline_VITIS_LOOP_39_1_fu_233_m_axi_gmem1_ARBURST;
wire   [1:0] grp_fir_fixed_Pipeline_VITIS_LOOP_39_1_fu_233_m_axi_gmem1_ARLOCK;
wire   [3:0] grp_fir_fixed_Pipeline_VITIS_LOOP_39_1_fu_233_m_axi_gmem1_ARCACHE;
wire   [2:0] grp_fir_fixed_Pipeline_VITIS_LOOP_39_1_fu_233_m_axi_gmem1_ARPROT;
wire   [3:0] grp_fir_fixed_Pipeline_VITIS_LOOP_39_1_fu_233_m_axi_gmem1_ARQOS;
wire   [3:0] grp_fir_fixed_Pipeline_VITIS_LOOP_39_1_fu_233_m_axi_gmem1_ARREGION;
wire   [0:0] grp_fir_fixed_Pipeline_VITIS_LOOP_39_1_fu_233_m_axi_gmem1_ARUSER;
wire    grp_fir_fixed_Pipeline_VITIS_LOOP_39_1_fu_233_m_axi_gmem1_RREADY;
wire    grp_fir_fixed_Pipeline_VITIS_LOOP_39_1_fu_233_m_axi_gmem1_BREADY;
wire    gmem0_AWREADY;
wire    gmem0_WREADY;
reg    gmem0_ARVALID;
wire    gmem0_ARREADY;
reg   [63:0] gmem0_ARADDR;
reg   [0:0] gmem0_ARID;
reg   [31:0] gmem0_ARLEN;
reg   [2:0] gmem0_ARSIZE;
reg   [1:0] gmem0_ARBURST;
reg   [1:0] gmem0_ARLOCK;
reg   [3:0] gmem0_ARCACHE;
reg   [2:0] gmem0_ARPROT;
reg   [3:0] gmem0_ARQOS;
reg   [3:0] gmem0_ARREGION;
reg   [0:0] gmem0_ARUSER;
wire    gmem0_RVALID;
reg    gmem0_RREADY;
wire   [31:0] gmem0_RDATA;
wire    gmem0_RLAST;
wire   [0:0] gmem0_RID;
wire   [0:0] gmem0_RUSER;
wire   [1:0] gmem0_RRESP;
wire    gmem0_BVALID;
wire   [1:0] gmem0_BRESP;
wire   [0:0] gmem0_BID;
wire   [0:0] gmem0_BUSER;
reg    gmem1_AWVALID;
wire    gmem1_AWREADY;
reg   [63:0] gmem1_AWADDR;
reg   [0:0] gmem1_AWID;
reg   [31:0] gmem1_AWLEN;
reg   [2:0] gmem1_AWSIZE;
reg   [1:0] gmem1_AWBURST;
reg   [1:0] gmem1_AWLOCK;
reg   [3:0] gmem1_AWCACHE;
reg   [2:0] gmem1_AWPROT;
reg   [3:0] gmem1_AWQOS;
reg   [3:0] gmem1_AWREGION;
reg   [0:0] gmem1_AWUSER;
reg    gmem1_WVALID;
wire    gmem1_WREADY;
wire    gmem1_ARREADY;
wire    gmem1_RVALID;
wire   [31:0] gmem1_RDATA;
wire    gmem1_RLAST;
wire   [0:0] gmem1_RID;
wire   [0:0] gmem1_RUSER;
wire   [1:0] gmem1_RRESP;
wire    gmem1_BVALID;
reg    gmem1_BREADY;
wire   [1:0] gmem1_BRESP;
wire   [0:0] gmem1_BID;
wire   [0:0] gmem1_BUSER;
reg    grp_fir_fixed_Pipeline_VITIS_LOOP_39_1_fu_233_ap_start_reg;
wire    ap_CS_fsm_state9;
wire    ap_CS_fsm_state10;
wire  signed [63:0] sext_ln39_fu_409_p1;
wire  signed [63:0] sext_ln39_1_fu_419_p1;
reg   [14:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
reg    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
reg    ap_ST_fsm_state8_blk;
wire    ap_ST_fsm_state9_blk;
reg    ap_ST_fsm_state10_blk;
wire    ap_ST_fsm_state11_blk;
wire    ap_ST_fsm_state12_blk;
wire    ap_ST_fsm_state13_blk;
wire    ap_ST_fsm_state14_blk;
reg    ap_ST_fsm_state15_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 15'd1;
#0 grp_fir_fixed_Pipeline_VITIS_LOOP_39_1_fu_233_ap_start_reg = 1'b0;
end

fir_fixed_fir_fixed_Pipeline_VITIS_LOOP_39_1 grp_fir_fixed_Pipeline_VITIS_LOOP_39_1_fu_233(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_fir_fixed_Pipeline_VITIS_LOOP_39_1_fu_233_ap_start),
    .ap_done(grp_fir_fixed_Pipeline_VITIS_LOOP_39_1_fu_233_ap_done),
    .ap_idle(grp_fir_fixed_Pipeline_VITIS_LOOP_39_1_fu_233_ap_idle),
    .ap_ready(grp_fir_fixed_Pipeline_VITIS_LOOP_39_1_fu_233_ap_ready),
    .m_axi_gmem0_AWVALID(grp_fir_fixed_Pipeline_VITIS_LOOP_39_1_fu_233_m_axi_gmem0_AWVALID),
    .m_axi_gmem0_AWREADY(1'b0),
    .m_axi_gmem0_AWADDR(grp_fir_fixed_Pipeline_VITIS_LOOP_39_1_fu_233_m_axi_gmem0_AWADDR),
    .m_axi_gmem0_AWID(grp_fir_fixed_Pipeline_VITIS_LOOP_39_1_fu_233_m_axi_gmem0_AWID),
    .m_axi_gmem0_AWLEN(grp_fir_fixed_Pipeline_VITIS_LOOP_39_1_fu_233_m_axi_gmem0_AWLEN),
    .m_axi_gmem0_AWSIZE(grp_fir_fixed_Pipeline_VITIS_LOOP_39_1_fu_233_m_axi_gmem0_AWSIZE),
    .m_axi_gmem0_AWBURST(grp_fir_fixed_Pipeline_VITIS_LOOP_39_1_fu_233_m_axi_gmem0_AWBURST),
    .m_axi_gmem0_AWLOCK(grp_fir_fixed_Pipeline_VITIS_LOOP_39_1_fu_233_m_axi_gmem0_AWLOCK),
    .m_axi_gmem0_AWCACHE(grp_fir_fixed_Pipeline_VITIS_LOOP_39_1_fu_233_m_axi_gmem0_AWCACHE),
    .m_axi_gmem0_AWPROT(grp_fir_fixed_Pipeline_VITIS_LOOP_39_1_fu_233_m_axi_gmem0_AWPROT),
    .m_axi_gmem0_AWQOS(grp_fir_fixed_Pipeline_VITIS_LOOP_39_1_fu_233_m_axi_gmem0_AWQOS),
    .m_axi_gmem0_AWREGION(grp_fir_fixed_Pipeline_VITIS_LOOP_39_1_fu_233_m_axi_gmem0_AWREGION),
    .m_axi_gmem0_AWUSER(grp_fir_fixed_Pipeline_VITIS_LOOP_39_1_fu_233_m_axi_gmem0_AWUSER),
    .m_axi_gmem0_WVALID(grp_fir_fixed_Pipeline_VITIS_LOOP_39_1_fu_233_m_axi_gmem0_WVALID),
    .m_axi_gmem0_WREADY(1'b0),
    .m_axi_gmem0_WDATA(grp_fir_fixed_Pipeline_VITIS_LOOP_39_1_fu_233_m_axi_gmem0_WDATA),
    .m_axi_gmem0_WSTRB(grp_fir_fixed_Pipeline_VITIS_LOOP_39_1_fu_233_m_axi_gmem0_WSTRB),
    .m_axi_gmem0_WLAST(grp_fir_fixed_Pipeline_VITIS_LOOP_39_1_fu_233_m_axi_gmem0_WLAST),
    .m_axi_gmem0_WID(grp_fir_fixed_Pipeline_VITIS_LOOP_39_1_fu_233_m_axi_gmem0_WID),
    .m_axi_gmem0_WUSER(grp_fir_fixed_Pipeline_VITIS_LOOP_39_1_fu_233_m_axi_gmem0_WUSER),
    .m_axi_gmem0_ARVALID(grp_fir_fixed_Pipeline_VITIS_LOOP_39_1_fu_233_m_axi_gmem0_ARVALID),
    .m_axi_gmem0_ARREADY(gmem0_ARREADY),
    .m_axi_gmem0_ARADDR(grp_fir_fixed_Pipeline_VITIS_LOOP_39_1_fu_233_m_axi_gmem0_ARADDR),
    .m_axi_gmem0_ARID(grp_fir_fixed_Pipeline_VITIS_LOOP_39_1_fu_233_m_axi_gmem0_ARID),
    .m_axi_gmem0_ARLEN(grp_fir_fixed_Pipeline_VITIS_LOOP_39_1_fu_233_m_axi_gmem0_ARLEN),
    .m_axi_gmem0_ARSIZE(grp_fir_fixed_Pipeline_VITIS_LOOP_39_1_fu_233_m_axi_gmem0_ARSIZE),
    .m_axi_gmem0_ARBURST(grp_fir_fixed_Pipeline_VITIS_LOOP_39_1_fu_233_m_axi_gmem0_ARBURST),
    .m_axi_gmem0_ARLOCK(grp_fir_fixed_Pipeline_VITIS_LOOP_39_1_fu_233_m_axi_gmem0_ARLOCK),
    .m_axi_gmem0_ARCACHE(grp_fir_fixed_Pipeline_VITIS_LOOP_39_1_fu_233_m_axi_gmem0_ARCACHE),
    .m_axi_gmem0_ARPROT(grp_fir_fixed_Pipeline_VITIS_LOOP_39_1_fu_233_m_axi_gmem0_ARPROT),
    .m_axi_gmem0_ARQOS(grp_fir_fixed_Pipeline_VITIS_LOOP_39_1_fu_233_m_axi_gmem0_ARQOS),
    .m_axi_gmem0_ARREGION(grp_fir_fixed_Pipeline_VITIS_LOOP_39_1_fu_233_m_axi_gmem0_ARREGION),
    .m_axi_gmem0_ARUSER(grp_fir_fixed_Pipeline_VITIS_LOOP_39_1_fu_233_m_axi_gmem0_ARUSER),
    .m_axi_gmem0_RVALID(gmem0_RVALID),
    .m_axi_gmem0_RREADY(grp_fir_fixed_Pipeline_VITIS_LOOP_39_1_fu_233_m_axi_gmem0_RREADY),
    .m_axi_gmem0_RDATA(gmem0_RDATA),
    .m_axi_gmem0_RLAST(gmem0_RLAST),
    .m_axi_gmem0_RID(gmem0_RID),
    .m_axi_gmem0_RUSER(gmem0_RUSER),
    .m_axi_gmem0_RRESP(gmem0_RRESP),
    .m_axi_gmem0_BVALID(1'b0),
    .m_axi_gmem0_BREADY(grp_fir_fixed_Pipeline_VITIS_LOOP_39_1_fu_233_m_axi_gmem0_BREADY),
    .m_axi_gmem0_BRESP(2'd0),
    .m_axi_gmem0_BID(1'd0),
    .m_axi_gmem0_BUSER(1'd0),
    .m_axi_gmem1_AWVALID(grp_fir_fixed_Pipeline_VITIS_LOOP_39_1_fu_233_m_axi_gmem1_AWVALID),
    .m_axi_gmem1_AWREADY(gmem1_AWREADY),
    .m_axi_gmem1_AWADDR(grp_fir_fixed_Pipeline_VITIS_LOOP_39_1_fu_233_m_axi_gmem1_AWADDR),
    .m_axi_gmem1_AWID(grp_fir_fixed_Pipeline_VITIS_LOOP_39_1_fu_233_m_axi_gmem1_AWID),
    .m_axi_gmem1_AWLEN(grp_fir_fixed_Pipeline_VITIS_LOOP_39_1_fu_233_m_axi_gmem1_AWLEN),
    .m_axi_gmem1_AWSIZE(grp_fir_fixed_Pipeline_VITIS_LOOP_39_1_fu_233_m_axi_gmem1_AWSIZE),
    .m_axi_gmem1_AWBURST(grp_fir_fixed_Pipeline_VITIS_LOOP_39_1_fu_233_m_axi_gmem1_AWBURST),
    .m_axi_gmem1_AWLOCK(grp_fir_fixed_Pipeline_VITIS_LOOP_39_1_fu_233_m_axi_gmem1_AWLOCK),
    .m_axi_gmem1_AWCACHE(grp_fir_fixed_Pipeline_VITIS_LOOP_39_1_fu_233_m_axi_gmem1_AWCACHE),
    .m_axi_gmem1_AWPROT(grp_fir_fixed_Pipeline_VITIS_LOOP_39_1_fu_233_m_axi_gmem1_AWPROT),
    .m_axi_gmem1_AWQOS(grp_fir_fixed_Pipeline_VITIS_LOOP_39_1_fu_233_m_axi_gmem1_AWQOS),
    .m_axi_gmem1_AWREGION(grp_fir_fixed_Pipeline_VITIS_LOOP_39_1_fu_233_m_axi_gmem1_AWREGION),
    .m_axi_gmem1_AWUSER(grp_fir_fixed_Pipeline_VITIS_LOOP_39_1_fu_233_m_axi_gmem1_AWUSER),
    .m_axi_gmem1_WVALID(grp_fir_fixed_Pipeline_VITIS_LOOP_39_1_fu_233_m_axi_gmem1_WVALID),
    .m_axi_gmem1_WREADY(gmem1_WREADY),
    .m_axi_gmem1_WDATA(grp_fir_fixed_Pipeline_VITIS_LOOP_39_1_fu_233_m_axi_gmem1_WDATA),
    .m_axi_gmem1_WSTRB(grp_fir_fixed_Pipeline_VITIS_LOOP_39_1_fu_233_m_axi_gmem1_WSTRB),
    .m_axi_gmem1_WLAST(grp_fir_fixed_Pipeline_VITIS_LOOP_39_1_fu_233_m_axi_gmem1_WLAST),
    .m_axi_gmem1_WID(grp_fir_fixed_Pipeline_VITIS_LOOP_39_1_fu_233_m_axi_gmem1_WID),
    .m_axi_gmem1_WUSER(grp_fir_fixed_Pipeline_VITIS_LOOP_39_1_fu_233_m_axi_gmem1_WUSER),
    .m_axi_gmem1_ARVALID(grp_fir_fixed_Pipeline_VITIS_LOOP_39_1_fu_233_m_axi_gmem1_ARVALID),
    .m_axi_gmem1_ARREADY(1'b0),
    .m_axi_gmem1_ARADDR(grp_fir_fixed_Pipeline_VITIS_LOOP_39_1_fu_233_m_axi_gmem1_ARADDR),
    .m_axi_gmem1_ARID(grp_fir_fixed_Pipeline_VITIS_LOOP_39_1_fu_233_m_axi_gmem1_ARID),
    .m_axi_gmem1_ARLEN(grp_fir_fixed_Pipeline_VITIS_LOOP_39_1_fu_233_m_axi_gmem1_ARLEN),
    .m_axi_gmem1_ARSIZE(grp_fir_fixed_Pipeline_VITIS_LOOP_39_1_fu_233_m_axi_gmem1_ARSIZE),
    .m_axi_gmem1_ARBURST(grp_fir_fixed_Pipeline_VITIS_LOOP_39_1_fu_233_m_axi_gmem1_ARBURST),
    .m_axi_gmem1_ARLOCK(grp_fir_fixed_Pipeline_VITIS_LOOP_39_1_fu_233_m_axi_gmem1_ARLOCK),
    .m_axi_gmem1_ARCACHE(grp_fir_fixed_Pipeline_VITIS_LOOP_39_1_fu_233_m_axi_gmem1_ARCACHE),
    .m_axi_gmem1_ARPROT(grp_fir_fixed_Pipeline_VITIS_LOOP_39_1_fu_233_m_axi_gmem1_ARPROT),
    .m_axi_gmem1_ARQOS(grp_fir_fixed_Pipeline_VITIS_LOOP_39_1_fu_233_m_axi_gmem1_ARQOS),
    .m_axi_gmem1_ARREGION(grp_fir_fixed_Pipeline_VITIS_LOOP_39_1_fu_233_m_axi_gmem1_ARREGION),
    .m_axi_gmem1_ARUSER(grp_fir_fixed_Pipeline_VITIS_LOOP_39_1_fu_233_m_axi_gmem1_ARUSER),
    .m_axi_gmem1_RVALID(1'b0),
    .m_axi_gmem1_RREADY(grp_fir_fixed_Pipeline_VITIS_LOOP_39_1_fu_233_m_axi_gmem1_RREADY),
    .m_axi_gmem1_RDATA(32'd0),
    .m_axi_gmem1_RLAST(1'b0),
    .m_axi_gmem1_RID(1'd0),
    .m_axi_gmem1_RUSER(1'd0),
    .m_axi_gmem1_RRESP(2'd0),
    .m_axi_gmem1_BVALID(gmem1_BVALID),
    .m_axi_gmem1_BREADY(grp_fir_fixed_Pipeline_VITIS_LOOP_39_1_fu_233_m_axi_gmem1_BREADY),
    .m_axi_gmem1_BRESP(gmem1_BRESP),
    .m_axi_gmem1_BID(gmem1_BID),
    .m_axi_gmem1_BUSER(gmem1_BUSER),
    .sext_ln39_1(trunc_ln39_1_reg_435),
    .sext_ln39(trunc_ln_reg_429)
);

fir_fixed_control_s_axi #(
    .C_S_AXI_ADDR_WIDTH( C_S_AXI_CONTROL_ADDR_WIDTH ),
    .C_S_AXI_DATA_WIDTH( C_S_AXI_CONTROL_DATA_WIDTH ))
control_s_axi_U(
    .AWVALID(s_axi_control_AWVALID),
    .AWREADY(s_axi_control_AWREADY),
    .AWADDR(s_axi_control_AWADDR),
    .WVALID(s_axi_control_WVALID),
    .WREADY(s_axi_control_WREADY),
    .WDATA(s_axi_control_WDATA),
    .WSTRB(s_axi_control_WSTRB),
    .ARVALID(s_axi_control_ARVALID),
    .ARREADY(s_axi_control_ARREADY),
    .ARADDR(s_axi_control_ARADDR),
    .RVALID(s_axi_control_RVALID),
    .RREADY(s_axi_control_RREADY),
    .RDATA(s_axi_control_RDATA),
    .RRESP(s_axi_control_RRESP),
    .BVALID(s_axi_control_BVALID),
    .BREADY(s_axi_control_BREADY),
    .BRESP(s_axi_control_BRESP),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .input_r(input_r),
    .output_r(output_r),
    .ap_start(ap_start),
    .interrupt(interrupt),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_idle(ap_idle)
);

fir_fixed_gmem0_m_axi #(
    .CONSERVATIVE( 0 ),
    .USER_DW( 32 ),
    .USER_AW( 64 ),
    .USER_MAXREQS( 5 ),
    .NUM_READ_OUTSTANDING( 16 ),
    .NUM_WRITE_OUTSTANDING( 16 ),
    .MAX_READ_BURST_LENGTH( 16 ),
    .MAX_WRITE_BURST_LENGTH( 16 ),
    .C_M_AXI_ID_WIDTH( C_M_AXI_GMEM0_ID_WIDTH ),
    .C_M_AXI_ADDR_WIDTH( C_M_AXI_GMEM0_ADDR_WIDTH ),
    .C_M_AXI_DATA_WIDTH( C_M_AXI_GMEM0_DATA_WIDTH ),
    .C_M_AXI_AWUSER_WIDTH( C_M_AXI_GMEM0_AWUSER_WIDTH ),
    .C_M_AXI_ARUSER_WIDTH( C_M_AXI_GMEM0_ARUSER_WIDTH ),
    .C_M_AXI_WUSER_WIDTH( C_M_AXI_GMEM0_WUSER_WIDTH ),
    .C_M_AXI_RUSER_WIDTH( C_M_AXI_GMEM0_RUSER_WIDTH ),
    .C_M_AXI_BUSER_WIDTH( C_M_AXI_GMEM0_BUSER_WIDTH ),
    .C_USER_VALUE( C_M_AXI_GMEM0_USER_VALUE ),
    .C_PROT_VALUE( C_M_AXI_GMEM0_PROT_VALUE ),
    .C_CACHE_VALUE( C_M_AXI_GMEM0_CACHE_VALUE ))
gmem0_m_axi_U(
    .AWVALID(m_axi_gmem0_AWVALID),
    .AWREADY(m_axi_gmem0_AWREADY),
    .AWADDR(m_axi_gmem0_AWADDR),
    .AWID(m_axi_gmem0_AWID),
    .AWLEN(m_axi_gmem0_AWLEN),
    .AWSIZE(m_axi_gmem0_AWSIZE),
    .AWBURST(m_axi_gmem0_AWBURST),
    .AWLOCK(m_axi_gmem0_AWLOCK),
    .AWCACHE(m_axi_gmem0_AWCACHE),
    .AWPROT(m_axi_gmem0_AWPROT),
    .AWQOS(m_axi_gmem0_AWQOS),
    .AWREGION(m_axi_gmem0_AWREGION),
    .AWUSER(m_axi_gmem0_AWUSER),
    .WVALID(m_axi_gmem0_WVALID),
    .WREADY(m_axi_gmem0_WREADY),
    .WDATA(m_axi_gmem0_WDATA),
    .WSTRB(m_axi_gmem0_WSTRB),
    .WLAST(m_axi_gmem0_WLAST),
    .WID(m_axi_gmem0_WID),
    .WUSER(m_axi_gmem0_WUSER),
    .ARVALID(m_axi_gmem0_ARVALID),
    .ARREADY(m_axi_gmem0_ARREADY),
    .ARADDR(m_axi_gmem0_ARADDR),
    .ARID(m_axi_gmem0_ARID),
    .ARLEN(m_axi_gmem0_ARLEN),
    .ARSIZE(m_axi_gmem0_ARSIZE),
    .ARBURST(m_axi_gmem0_ARBURST),
    .ARLOCK(m_axi_gmem0_ARLOCK),
    .ARCACHE(m_axi_gmem0_ARCACHE),
    .ARPROT(m_axi_gmem0_ARPROT),
    .ARQOS(m_axi_gmem0_ARQOS),
    .ARREGION(m_axi_gmem0_ARREGION),
    .ARUSER(m_axi_gmem0_ARUSER),
    .RVALID(m_axi_gmem0_RVALID),
    .RREADY(m_axi_gmem0_RREADY),
    .RDATA(m_axi_gmem0_RDATA),
    .RLAST(m_axi_gmem0_RLAST),
    .RID(m_axi_gmem0_RID),
    .RUSER(m_axi_gmem0_RUSER),
    .RRESP(m_axi_gmem0_RRESP),
    .BVALID(m_axi_gmem0_BVALID),
    .BREADY(m_axi_gmem0_BREADY),
    .BRESP(m_axi_gmem0_BRESP),
    .BID(m_axi_gmem0_BID),
    .BUSER(m_axi_gmem0_BUSER),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .I_ARVALID(gmem0_ARVALID),
    .I_ARREADY(gmem0_ARREADY),
    .I_ARADDR(gmem0_ARADDR),
    .I_ARID(gmem0_ARID),
    .I_ARLEN(gmem0_ARLEN),
    .I_ARSIZE(gmem0_ARSIZE),
    .I_ARLOCK(gmem0_ARLOCK),
    .I_ARCACHE(gmem0_ARCACHE),
    .I_ARQOS(gmem0_ARQOS),
    .I_ARPROT(gmem0_ARPROT),
    .I_ARUSER(gmem0_ARUSER),
    .I_ARBURST(gmem0_ARBURST),
    .I_ARREGION(gmem0_ARREGION),
    .I_RVALID(gmem0_RVALID),
    .I_RREADY(gmem0_RREADY),
    .I_RDATA(gmem0_RDATA),
    .I_RID(gmem0_RID),
    .I_RUSER(gmem0_RUSER),
    .I_RRESP(gmem0_RRESP),
    .I_RLAST(gmem0_RLAST),
    .I_AWVALID(1'b0),
    .I_AWREADY(gmem0_AWREADY),
    .I_AWADDR(64'd0),
    .I_AWID(1'd0),
    .I_AWLEN(32'd0),
    .I_AWSIZE(3'd0),
    .I_AWLOCK(2'd0),
    .I_AWCACHE(4'd0),
    .I_AWQOS(4'd0),
    .I_AWPROT(3'd0),
    .I_AWUSER(1'd0),
    .I_AWBURST(2'd0),
    .I_AWREGION(4'd0),
    .I_WVALID(1'b0),
    .I_WREADY(gmem0_WREADY),
    .I_WDATA(32'd0),
    .I_WID(1'd0),
    .I_WUSER(1'd0),
    .I_WLAST(1'b0),
    .I_WSTRB(4'd0),
    .I_BVALID(gmem0_BVALID),
    .I_BREADY(1'b0),
    .I_BRESP(gmem0_BRESP),
    .I_BID(gmem0_BID),
    .I_BUSER(gmem0_BUSER)
);

fir_fixed_gmem1_m_axi #(
    .CONSERVATIVE( 0 ),
    .USER_DW( 32 ),
    .USER_AW( 64 ),
    .USER_MAXREQS( 5 ),
    .NUM_READ_OUTSTANDING( 16 ),
    .NUM_WRITE_OUTSTANDING( 16 ),
    .MAX_READ_BURST_LENGTH( 16 ),
    .MAX_WRITE_BURST_LENGTH( 16 ),
    .C_M_AXI_ID_WIDTH( C_M_AXI_GMEM1_ID_WIDTH ),
    .C_M_AXI_ADDR_WIDTH( C_M_AXI_GMEM1_ADDR_WIDTH ),
    .C_M_AXI_DATA_WIDTH( C_M_AXI_GMEM1_DATA_WIDTH ),
    .C_M_AXI_AWUSER_WIDTH( C_M_AXI_GMEM1_AWUSER_WIDTH ),
    .C_M_AXI_ARUSER_WIDTH( C_M_AXI_GMEM1_ARUSER_WIDTH ),
    .C_M_AXI_WUSER_WIDTH( C_M_AXI_GMEM1_WUSER_WIDTH ),
    .C_M_AXI_RUSER_WIDTH( C_M_AXI_GMEM1_RUSER_WIDTH ),
    .C_M_AXI_BUSER_WIDTH( C_M_AXI_GMEM1_BUSER_WIDTH ),
    .C_USER_VALUE( C_M_AXI_GMEM1_USER_VALUE ),
    .C_PROT_VALUE( C_M_AXI_GMEM1_PROT_VALUE ),
    .C_CACHE_VALUE( C_M_AXI_GMEM1_CACHE_VALUE ))
gmem1_m_axi_U(
    .AWVALID(m_axi_gmem1_AWVALID),
    .AWREADY(m_axi_gmem1_AWREADY),
    .AWADDR(m_axi_gmem1_AWADDR),
    .AWID(m_axi_gmem1_AWID),
    .AWLEN(m_axi_gmem1_AWLEN),
    .AWSIZE(m_axi_gmem1_AWSIZE),
    .AWBURST(m_axi_gmem1_AWBURST),
    .AWLOCK(m_axi_gmem1_AWLOCK),
    .AWCACHE(m_axi_gmem1_AWCACHE),
    .AWPROT(m_axi_gmem1_AWPROT),
    .AWQOS(m_axi_gmem1_AWQOS),
    .AWREGION(m_axi_gmem1_AWREGION),
    .AWUSER(m_axi_gmem1_AWUSER),
    .WVALID(m_axi_gmem1_WVALID),
    .WREADY(m_axi_gmem1_WREADY),
    .WDATA(m_axi_gmem1_WDATA),
    .WSTRB(m_axi_gmem1_WSTRB),
    .WLAST(m_axi_gmem1_WLAST),
    .WID(m_axi_gmem1_WID),
    .WUSER(m_axi_gmem1_WUSER),
    .ARVALID(m_axi_gmem1_ARVALID),
    .ARREADY(m_axi_gmem1_ARREADY),
    .ARADDR(m_axi_gmem1_ARADDR),
    .ARID(m_axi_gmem1_ARID),
    .ARLEN(m_axi_gmem1_ARLEN),
    .ARSIZE(m_axi_gmem1_ARSIZE),
    .ARBURST(m_axi_gmem1_ARBURST),
    .ARLOCK(m_axi_gmem1_ARLOCK),
    .ARCACHE(m_axi_gmem1_ARCACHE),
    .ARPROT(m_axi_gmem1_ARPROT),
    .ARQOS(m_axi_gmem1_ARQOS),
    .ARREGION(m_axi_gmem1_ARREGION),
    .ARUSER(m_axi_gmem1_ARUSER),
    .RVALID(m_axi_gmem1_RVALID),
    .RREADY(m_axi_gmem1_RREADY),
    .RDATA(m_axi_gmem1_RDATA),
    .RLAST(m_axi_gmem1_RLAST),
    .RID(m_axi_gmem1_RID),
    .RUSER(m_axi_gmem1_RUSER),
    .RRESP(m_axi_gmem1_RRESP),
    .BVALID(m_axi_gmem1_BVALID),
    .BREADY(m_axi_gmem1_BREADY),
    .BRESP(m_axi_gmem1_BRESP),
    .BID(m_axi_gmem1_BID),
    .BUSER(m_axi_gmem1_BUSER),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .I_ARVALID(1'b0),
    .I_ARREADY(gmem1_ARREADY),
    .I_ARADDR(64'd0),
    .I_ARID(1'd0),
    .I_ARLEN(32'd0),
    .I_ARSIZE(3'd0),
    .I_ARLOCK(2'd0),
    .I_ARCACHE(4'd0),
    .I_ARQOS(4'd0),
    .I_ARPROT(3'd0),
    .I_ARUSER(1'd0),
    .I_ARBURST(2'd0),
    .I_ARREGION(4'd0),
    .I_RVALID(gmem1_RVALID),
    .I_RREADY(1'b0),
    .I_RDATA(gmem1_RDATA),
    .I_RID(gmem1_RID),
    .I_RUSER(gmem1_RUSER),
    .I_RRESP(gmem1_RRESP),
    .I_RLAST(gmem1_RLAST),
    .I_AWVALID(gmem1_AWVALID),
    .I_AWREADY(gmem1_AWREADY),
    .I_AWADDR(gmem1_AWADDR),
    .I_AWID(gmem1_AWID),
    .I_AWLEN(gmem1_AWLEN),
    .I_AWSIZE(gmem1_AWSIZE),
    .I_AWLOCK(gmem1_AWLOCK),
    .I_AWCACHE(gmem1_AWCACHE),
    .I_AWQOS(gmem1_AWQOS),
    .I_AWPROT(gmem1_AWPROT),
    .I_AWUSER(gmem1_AWUSER),
    .I_AWBURST(gmem1_AWBURST),
    .I_AWREGION(gmem1_AWREGION),
    .I_WVALID(gmem1_WVALID),
    .I_WREADY(gmem1_WREADY),
    .I_WDATA(grp_fir_fixed_Pipeline_VITIS_LOOP_39_1_fu_233_m_axi_gmem1_WDATA),
    .I_WID(grp_fir_fixed_Pipeline_VITIS_LOOP_39_1_fu_233_m_axi_gmem1_WID),
    .I_WUSER(grp_fir_fixed_Pipeline_VITIS_LOOP_39_1_fu_233_m_axi_gmem1_WUSER),
    .I_WLAST(grp_fir_fixed_Pipeline_VITIS_LOOP_39_1_fu_233_m_axi_gmem1_WLAST),
    .I_WSTRB(grp_fir_fixed_Pipeline_VITIS_LOOP_39_1_fu_233_m_axi_gmem1_WSTRB),
    .I_BVALID(gmem1_BVALID),
    .I_BREADY(gmem1_BREADY),
    .I_BRESP(gmem1_BRESP),
    .I_BID(gmem1_BID),
    .I_BUSER(gmem1_BUSER)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_fir_fixed_Pipeline_VITIS_LOOP_39_1_fu_233_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state9)) begin
            grp_fir_fixed_Pipeline_VITIS_LOOP_39_1_fu_233_ap_start_reg <= 1'b1;
        end else if ((grp_fir_fixed_Pipeline_VITIS_LOOP_39_1_fu_233_ap_ready == 1'b1)) begin
            grp_fir_fixed_Pipeline_VITIS_LOOP_39_1_fu_233_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        trunc_ln39_1_reg_435 <= {{output_r[63:2]}};
        trunc_ln_reg_429 <= {{input_r[63:2]}};
    end
end

always @ (*) begin
    if ((grp_fir_fixed_Pipeline_VITIS_LOOP_39_1_fu_233_ap_done == 1'b0)) begin
        ap_ST_fsm_state10_blk = 1'b1;
    end else begin
        ap_ST_fsm_state10_blk = 1'b0;
    end
end

assign ap_ST_fsm_state11_blk = 1'b0;

assign ap_ST_fsm_state12_blk = 1'b0;

assign ap_ST_fsm_state13_blk = 1'b0;

assign ap_ST_fsm_state14_blk = 1'b0;

always @ (*) begin
    if ((gmem1_BVALID == 1'b0)) begin
        ap_ST_fsm_state15_blk = 1'b1;
    end else begin
        ap_ST_fsm_state15_blk = 1'b0;
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if ((gmem0_ARREADY == 1'b0)) begin
        ap_ST_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_fsm_state2_blk = 1'b0;
    end
end

assign ap_ST_fsm_state3_blk = 1'b0;

assign ap_ST_fsm_state4_blk = 1'b0;

assign ap_ST_fsm_state5_blk = 1'b0;

assign ap_ST_fsm_state6_blk = 1'b0;

assign ap_ST_fsm_state7_blk = 1'b0;

always @ (*) begin
    if ((gmem1_AWREADY == 1'b0)) begin
        ap_ST_fsm_state8_blk = 1'b1;
    end else begin
        ap_ST_fsm_state8_blk = 1'b0;
    end
end

assign ap_ST_fsm_state9_blk = 1'b0;

always @ (*) begin
    if (((gmem1_BVALID == 1'b1) & (1'b1 == ap_CS_fsm_state15))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((gmem1_BVALID == 1'b1) & (1'b1 == ap_CS_fsm_state15))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((gmem0_ARREADY == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        gmem0_ARADDR = sext_ln39_fu_409_p1;
    end else if (((1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state9))) begin
        gmem0_ARADDR = grp_fir_fixed_Pipeline_VITIS_LOOP_39_1_fu_233_m_axi_gmem0_ARADDR;
    end else begin
        gmem0_ARADDR = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state9))) begin
        gmem0_ARBURST = grp_fir_fixed_Pipeline_VITIS_LOOP_39_1_fu_233_m_axi_gmem0_ARBURST;
    end else begin
        gmem0_ARBURST = 2'd0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state9))) begin
        gmem0_ARCACHE = grp_fir_fixed_Pipeline_VITIS_LOOP_39_1_fu_233_m_axi_gmem0_ARCACHE;
    end else begin
        gmem0_ARCACHE = 4'd0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state9))) begin
        gmem0_ARID = grp_fir_fixed_Pipeline_VITIS_LOOP_39_1_fu_233_m_axi_gmem0_ARID;
    end else begin
        gmem0_ARID = 1'd0;
    end
end

always @ (*) begin
    if (((gmem0_ARREADY == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        gmem0_ARLEN = 32'd1024;
    end else if (((1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state9))) begin
        gmem0_ARLEN = grp_fir_fixed_Pipeline_VITIS_LOOP_39_1_fu_233_m_axi_gmem0_ARLEN;
    end else begin
        gmem0_ARLEN = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state9))) begin
        gmem0_ARLOCK = grp_fir_fixed_Pipeline_VITIS_LOOP_39_1_fu_233_m_axi_gmem0_ARLOCK;
    end else begin
        gmem0_ARLOCK = 2'd0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state9))) begin
        gmem0_ARPROT = grp_fir_fixed_Pipeline_VITIS_LOOP_39_1_fu_233_m_axi_gmem0_ARPROT;
    end else begin
        gmem0_ARPROT = 3'd0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state9))) begin
        gmem0_ARQOS = grp_fir_fixed_Pipeline_VITIS_LOOP_39_1_fu_233_m_axi_gmem0_ARQOS;
    end else begin
        gmem0_ARQOS = 4'd0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state9))) begin
        gmem0_ARREGION = grp_fir_fixed_Pipeline_VITIS_LOOP_39_1_fu_233_m_axi_gmem0_ARREGION;
    end else begin
        gmem0_ARREGION = 4'd0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state9))) begin
        gmem0_ARSIZE = grp_fir_fixed_Pipeline_VITIS_LOOP_39_1_fu_233_m_axi_gmem0_ARSIZE;
    end else begin
        gmem0_ARSIZE = 3'd0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state9))) begin
        gmem0_ARUSER = grp_fir_fixed_Pipeline_VITIS_LOOP_39_1_fu_233_m_axi_gmem0_ARUSER;
    end else begin
        gmem0_ARUSER = 1'd0;
    end
end

always @ (*) begin
    if (((gmem0_ARREADY == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        gmem0_ARVALID = 1'b1;
    end else if (((1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state9))) begin
        gmem0_ARVALID = grp_fir_fixed_Pipeline_VITIS_LOOP_39_1_fu_233_m_axi_gmem0_ARVALID;
    end else begin
        gmem0_ARVALID = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state9))) begin
        gmem0_RREADY = grp_fir_fixed_Pipeline_VITIS_LOOP_39_1_fu_233_m_axi_gmem0_RREADY;
    end else begin
        gmem0_RREADY = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        gmem0_blk_n_AR = m_axi_gmem0_ARREADY;
    end else begin
        gmem0_blk_n_AR = 1'b1;
    end
end

always @ (*) begin
    if (((gmem1_AWREADY == 1'b1) & (1'b1 == ap_CS_fsm_state8))) begin
        gmem1_AWADDR = sext_ln39_1_fu_419_p1;
    end else if (((1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state9))) begin
        gmem1_AWADDR = grp_fir_fixed_Pipeline_VITIS_LOOP_39_1_fu_233_m_axi_gmem1_AWADDR;
    end else begin
        gmem1_AWADDR = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state9))) begin
        gmem1_AWBURST = grp_fir_fixed_Pipeline_VITIS_LOOP_39_1_fu_233_m_axi_gmem1_AWBURST;
    end else begin
        gmem1_AWBURST = 2'd0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state9))) begin
        gmem1_AWCACHE = grp_fir_fixed_Pipeline_VITIS_LOOP_39_1_fu_233_m_axi_gmem1_AWCACHE;
    end else begin
        gmem1_AWCACHE = 4'd0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state9))) begin
        gmem1_AWID = grp_fir_fixed_Pipeline_VITIS_LOOP_39_1_fu_233_m_axi_gmem1_AWID;
    end else begin
        gmem1_AWID = 1'd0;
    end
end

always @ (*) begin
    if (((gmem1_AWREADY == 1'b1) & (1'b1 == ap_CS_fsm_state8))) begin
        gmem1_AWLEN = 32'd1024;
    end else if (((1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state9))) begin
        gmem1_AWLEN = grp_fir_fixed_Pipeline_VITIS_LOOP_39_1_fu_233_m_axi_gmem1_AWLEN;
    end else begin
        gmem1_AWLEN = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state9))) begin
        gmem1_AWLOCK = grp_fir_fixed_Pipeline_VITIS_LOOP_39_1_fu_233_m_axi_gmem1_AWLOCK;
    end else begin
        gmem1_AWLOCK = 2'd0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state9))) begin
        gmem1_AWPROT = grp_fir_fixed_Pipeline_VITIS_LOOP_39_1_fu_233_m_axi_gmem1_AWPROT;
    end else begin
        gmem1_AWPROT = 3'd0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state9))) begin
        gmem1_AWQOS = grp_fir_fixed_Pipeline_VITIS_LOOP_39_1_fu_233_m_axi_gmem1_AWQOS;
    end else begin
        gmem1_AWQOS = 4'd0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state9))) begin
        gmem1_AWREGION = grp_fir_fixed_Pipeline_VITIS_LOOP_39_1_fu_233_m_axi_gmem1_AWREGION;
    end else begin
        gmem1_AWREGION = 4'd0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state9))) begin
        gmem1_AWSIZE = grp_fir_fixed_Pipeline_VITIS_LOOP_39_1_fu_233_m_axi_gmem1_AWSIZE;
    end else begin
        gmem1_AWSIZE = 3'd0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state9))) begin
        gmem1_AWUSER = grp_fir_fixed_Pipeline_VITIS_LOOP_39_1_fu_233_m_axi_gmem1_AWUSER;
    end else begin
        gmem1_AWUSER = 1'd0;
    end
end

always @ (*) begin
    if (((gmem1_AWREADY == 1'b1) & (1'b1 == ap_CS_fsm_state8))) begin
        gmem1_AWVALID = 1'b1;
    end else if (((1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state9))) begin
        gmem1_AWVALID = grp_fir_fixed_Pipeline_VITIS_LOOP_39_1_fu_233_m_axi_gmem1_AWVALID;
    end else begin
        gmem1_AWVALID = 1'b0;
    end
end

always @ (*) begin
    if (((gmem1_BVALID == 1'b1) & (1'b1 == ap_CS_fsm_state15))) begin
        gmem1_BREADY = 1'b1;
    end else if (((1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state9))) begin
        gmem1_BREADY = grp_fir_fixed_Pipeline_VITIS_LOOP_39_1_fu_233_m_axi_gmem1_BREADY;
    end else begin
        gmem1_BREADY = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state9))) begin
        gmem1_WVALID = grp_fir_fixed_Pipeline_VITIS_LOOP_39_1_fu_233_m_axi_gmem1_WVALID;
    end else begin
        gmem1_WVALID = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        gmem1_blk_n_AW = m_axi_gmem1_AWREADY;
    end else begin
        gmem1_blk_n_AW = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state15)) begin
        gmem1_blk_n_B = m_axi_gmem1_BVALID;
    end else begin
        gmem1_blk_n_B = 1'b1;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((gmem0_ARREADY == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            if (((gmem1_AWREADY == 1'b1) & (1'b1 == ap_CS_fsm_state8))) begin
                ap_NS_fsm = ap_ST_fsm_state9;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state10 : begin
            if (((1'b1 == ap_CS_fsm_state10) & (grp_fir_fixed_Pipeline_VITIS_LOOP_39_1_fu_233_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state11;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state10;
            end
        end
        ap_ST_fsm_state11 : begin
            ap_NS_fsm = ap_ST_fsm_state12;
        end
        ap_ST_fsm_state12 : begin
            ap_NS_fsm = ap_ST_fsm_state13;
        end
        ap_ST_fsm_state13 : begin
            ap_NS_fsm = ap_ST_fsm_state14;
        end
        ap_ST_fsm_state14 : begin
            ap_NS_fsm = ap_ST_fsm_state15;
        end
        ap_ST_fsm_state15 : begin
            if (((gmem1_BVALID == 1'b1) & (1'b1 == ap_CS_fsm_state15))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state15;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state15 = ap_CS_fsm[32'd14];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign grp_fir_fixed_Pipeline_VITIS_LOOP_39_1_fu_233_ap_start = grp_fir_fixed_Pipeline_VITIS_LOOP_39_1_fu_233_ap_start_reg;

assign sext_ln39_1_fu_419_p1 = $signed(trunc_ln39_1_reg_435);

assign sext_ln39_fu_409_p1 = $signed(trunc_ln_reg_429);

endmodule //fir_fixed
